In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
import tensorflow as tf

In [ ]:
path_to_file = '/content/drive/MyDrive/Deep_learning-datasets/shakespeare.txt'

In [ ]:
text = open(path_to_file, 'r').read()

In [ ]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [ ]:
vocab = sorted(set(text))

In [ ]:
len(vocab)

84

In [ ]:
char_to_ind = {char:ind for ind, char in enumerate(vocab)}

In [ ]:
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [ ]:
ind_to_char = np.array(vocab)

In [ ]:
ind_to_char

array(['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1',
       '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?',
       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
       'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
       'w', 'x', 'y', 'z', '|', '}'], dtype='<U1')

In [ ]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [ ]:
encoded_text.shape

(5445609,)

In [ ]:
sample = text[:500]

In [ ]:
sample

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [ ]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

In [ ]:
seq_length = 120

In [ ]:
total_num_seq = len(text) // (seq_length+1)

In [ ]:
total_num_seq

45005

In [ ]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

In [ ]:
char_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>

In [ ]:
sequences = char_dataset.batch(seq_length+1, drop_remainder=True)

In [ ]:
def create_seq_targets(seq):
  input_txt = seq[:-1]
  target_txt = seq[1:]
  return input_txt, target_txt

In [ ]:
dataset = sequences.map(create_seq_targets)

In [ ]:
for input_text, target_text in dataset.take(1):
  print(input_text.numpy())
  print("".join(ind_to_char[input_text.numpy()]))
  print("\n")
  print(target_text.numpy())
  print("".join(ind_to_char[input_text.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


In [ ]:
batch_size = 128

In [ ]:
buffer_size = 10000

dataset = dataset.shuffle(buffer_size=buffer_size).batch(batch_size,drop_remainder=True)

In [ ]:
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(128, 120), dtype=tf.int64, name=None), TensorSpec(shape=(128, 120), dtype=tf.int64, name=None))>

In [ ]:
vocab_size = len(vocab)

In [ ]:
vocab_size

84

In [ ]:
embed_dim = 64

In [ ]:
rnn_neurons = 1026

In [ ]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [ ]:
def sparse_cat_loss(y_true,y_pred):
  return sparse_categorical_crossentropy(y_true,y_pred,from_logits=True)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense, Input

In [ ]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model = Sequential()

    # Define input shape using Input layer with None for sequence length
    model.add(Input(batch_shape=(batch_size, None), dtype='int32'))

    # Add Embedding layer
    model.add(Embedding(input_dim=vocab_size, output_dim=embed_dim))

    # Add GRU layer
    model.add(GRU(rnn_neurons, return_sequences=True, stateful=True, recurrent_initializer='glorot_uniform'))

    # Add Dense output layer
    model.add(Dense(vocab_size))

    # Compile the model
    model.compile(optimizer='adam', loss=sparse_categorical_crossentropy)

    return model

In [ ]:
model = create_model(
  vocab_size = vocab_size,
  embed_dim=embed_dim,
  rnn_neurons=rnn_neurons,
  batch_size=batch_size)

In [ ]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)              │ (128, None, 64)             │           5,376 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ gru_7 (GRU)                          │ (128, None, 1026)           │       3,361,176 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (128, None, 84)             │          86,268 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,452,820 (13.17 MB)

 Trainable params: 3,452,820 (13.17 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
for input_example_batch, target_example_batch in dataset.take(1):
  example_batch_predictions = model(input_example_batch)

In [ ]:
example_batch_predictions.shape

TensorShape([128, 120, 84])

In [ ]:
example_batch_predictions[0]

<tf.Tensor: shape=(120, 84), dtype=float32, numpy=
array([[-3.9721606e-03,  7.0593733e-04,  5.8469037e-03, ...,
         2.3789071e-03,  2.2865525e-03,  4.7768699e-04],
       [-6.1543575e-03,  4.6201411e-04, -3.0971679e-04, ...,
         2.0388025e-03,  1.0585216e-03, -4.1791829e-03],
       [-1.1427894e-03, -9.7906357e-04,  3.3751826e-04, ...,
         5.5850763e-03,  1.0398098e-03, -6.9363839e-03],
       ...,
       [ 1.3800102e-03, -6.3466872e-03,  2.2001899e-04, ...,
         1.9200466e-03,  5.4404984e-04,  2.1164017e-04],
       [ 9.5826844e-03,  3.7364676e-04,  8.1957849e-03, ...,
        -1.9350640e-05,  5.1784134e-03, -3.7628977e-04],
       [ 1.1341710e-02,  2.6023628e-03,  5.6076571e-03, ...,
         1.3893858e-03, -8.2425011e-04, -4.5020226e-03]], dtype=float32)>

In [ ]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [ ]:
sampled_indices = tf.squeeze(sampled_indices, axis=-1).numpy()

In [ ]:
ind_to_char[sampled_indices]

array(['D', 'S', 'g', 'f', '2', 'E', ':', '8', 'd', '8', 'K', '7', '>',
       '8', 'Z', '3', 'l', 'i', 'A', ')', 'P', 'D', 'J', '\n', 'c', '2',
       '2', 'Y', '6', 'd', '4', '`', 'c', 'j', 'n', '&', 'M', '(', ' ',
       'V', '!', 'x', '3', 'I', 'O', ',', 'G', ' ', 'R', 'h', '?', 'n',
       'Z', 'U', 'M', '`', '7', 'S', '>', 'T', 'J', 'e', 'K', 'Z', 'N',
       '<', 'k', '3', 'g', ':', 'C', 'G', 'Q', 'S', 'R', 'O', 'y', 'E',
       'Q', 'P', 'x', ',', 'p', 's', ',', '"', 'u', 'e', 'c', 'v', '!',
       '8', 'K', 'B', 'K', '>', 'z', 'v', 'L', 'Q', ';', 'Z', ',', 'z',
       ':', '}', 'x', '&', 'l', 's', 'm', 'a', 'q', '<', '|', 't', '_',
       'p', 'M', 'W'], dtype='<U1')

In [ ]:
epochs = 50

In [ ]:
model.fit(dataset, epochs=epochs)

Epoch 1/50
351/351 ━━━━━━━━━━━━━━━━━━━━ 48s 127ms/step - loss: 3.4273
Epoch 2/50
351/351 ━━━━━━━━━━━━━━━━━━━━ 83s 129ms/step - loss: 2.8165
Epoch 3/50
351/351 ━━━━━━━━━━━━━━━━━━━━ 81s 128ms/step - loss: 3.7602
Epoch 4/50
351/351 ━━━━━━━━━━━━━━━━━━━━ 82s 128ms/step - loss: 3.8586
Epoch 5/50
351/351 ━━━━━━━━━━━━━━━━━━━━ 82s 128ms/step - loss: 3.8453
Epoch 6/50
351/351 ━━━━━━━━━━━━━━━━━━━━ 83s 128ms/step - loss: 3.8724
Epoch 7/50
351/351 ━━━━━━━━━━━━━━━━━━━━ 81s 128ms/step - loss: 3.9395
Epoch 8/50
351/351 ━━━━━━━━━━━━━━━━━━━━ 47s 127ms/step - loss: 3.6980
Epoch 9/50
351/351 ━━━━━━━━━━━━━━━━━━━━ 48s 128ms/step - loss: 3.3155
Epoch 10/50
351/351 ━━━━━━━━━━━━━━━━━━━━ 81s 129ms/step - loss: 3.3793
Epoch 11/50
351/351 ━━━━━━━━━━━━━━━━━━━━ 47s 127ms/step - loss: 3.6946
Epoch 12/50
351/351 ━━━━━━━━━━━━━━━━━━━━ 82s 129ms/step - loss: 3.7335
Epoch 13/50
351/351 ━━━━━━━━━━━━━━━━━━━━ 82s 128ms/step - loss: 3.7261
Epoch 14/50
351/351 ━━━━━━━━━━━━━━━━━━━━ 83s 128ms/step - loss: 3.6787
Epoch 15/50
351

In [ ]:
model.save('/content/drive/MyDrive/Deep_learning-datasets/shakespeare_gen.h5')

In [ ]:
model2 = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)

# load the weights
model2.load_weights('/content/drive/MyDrive/Deep_learning-datasets/shakespeare_gen.h5')

# Build the model by passing the expected input shape
model2.build(tf.TensorShape([1, None]))

In [ ]:
model2.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (1, None, 64)               │           5,376 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ gru (GRU)                            │ (1, None, 1026)             │       3,361,176 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (1, None, 84)               │          86,268 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,452,820 (13.17 MB)

 Trainable params: 3,452,820 (13.17 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
def generate_text(model, start_seed, gen_size=500, temp=1.0):
    num_generate = gen_size
    input_eval = [char_to_ind[s] for s in start_seed]
    input_eval = tf.expand_dims(input_eval, 0)
    text_generated = []
    temperature = temp

    for i in range(num_generate):
        predictions = model(input_eval)
        predictions = tf.squeeze(predictions, 0)
        predictions = predictions / temperature
        predicted_id = tf.random.categorical(predictions, num_samples=1)[-1, 0].numpy()

        # Update the input with the predicted ID (corrected)
        input_eval = tf.expand_dims([predicted_id], 0)

        text_generated.append(ind_to_char[predicted_id])

    return start_seed + ''.join(text_generated)


In [ ]:
print(generate_text(model2,"JULIET",gen_size=1000))

JULIET

  THERSITES. Even so; not with a marbare soul that's i' th'
    office, to inform other had wot; but in his
    eyes are subjects with this land which his brethren was rebiked.  
  PAULINA. For God's sake! lod?
    What cannot be so crack'd, being a god's browher.
  GONZALO. To great, go with your worship any military means success,
    Straith up into regarded-stomach.
  ANTONIO. The son, whose rich heir?
    Come.                                        Exeunt with the DUKE OF YORK  and a holided Satracta's woman?
  SIR. It seems not actions, which I will be well of
    what-arm't is to do more contrary? Well, I will not break in.
  AGUECHEEK. An't please his finder sheets, and use.
  KING RICHARD. That both our kinsman, with a wrather.
    This ring, this foot again again. Pray you, what match born such sore. And what word?
  DUCHESS. Dost thou make in the nose that was the man
    By mine enemy?
  VALENTINE.'S. I' th' purple talentate I look'd on to thee
    For these forth 